apiVersion: v1
kind: ReplicationController
metadata:
  name: executor
spec:
  replicas: 2
  selector:
    app: executor
  template:
    metadata:
      name: executor
      labels:
        app: executor
    spec:
      containers:
      - name: executor
        image: vineethguna/executor:2.1.0
        ports:
        - containerPort: 3000