apiVersion: v1
kind: ReplicationController
metadata:
  name: executor
spec:
  replicas: 2
  selector:
    app: executor
  template:
    metadata:
      name: executor
      labels:
        app: executor
    spec:
      containers:
      - name: executor
        image: vineethguna/executor:2.1.0
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        ports:
        - containerPort: 3000